export const carInfoModel = {
  id: "",
  mark: "",
  model: "",
  year: "",
  mileage: "",
  engine: "",
  horsePower: "",
  color: "",
  price: "",
  currency: "",
  isConditional: false,
  isChangeable: false,
  isPartPayable: false,
  vin: "",
  isMax: false,
  abc: true,
  esp:false,
  mirrorControl:false,
  rainSensor:false,
  trc:false,
  turbo:false,
  sitControl:true,
  lightSensor:false,
  ebd:false,
  boardComputer:false,
  mirrorAutoControl:false,
  cruiseControl:false,
  moreInfoText:""
};

export const descriptionData = {
  leftBlockData: [
    "mark",
    "model",
    "year",
    "mileage",
    "engine",
    "horse Power",
    "color",
  ],
  rightBlockData: [
    "price",
    "currency",
    "Conditional",
    "Changeable",
    "PartPayable",
    "vin",
    "Max",
  ],
};
